### ISSUE TITLE
Returning errors

### ISSUE THREAD

**Issue by idkjs** [digitake/bs-promise-monad#4]
Can't seem to understand what this wants me to return;

```
type idTokenT = {
  idToken,
} and idToken = {jwtToken: string};

let decodeJwt = json => Json.Decode.{jwtToken: json |> field("jwtToken",string)}
let decodeToken = json => Json.Decode.{
  idToken: json |> field("idToken", decodeJwt),
};

type auth;
[@bs.module "@aws-amplify/auth/lib"] external auth: auth = "default";
[@bs.send] external getCurrentSession:(auth,unit)=> Js.Promise.t(Js.Json.t) = "currentSession";

let getJwtToken = () => {
    open PromiseMonad;
    getCurrentSession(auth,())
    >>= (response => {
        let jwtToken = decodeToken(response);
    Js.log(jwtToken);
    return(jwtToken);
  })
>>| (err => {
    let errMsg = err |> Js.Json.stringifyAny |> Js.Option.getWithDefault("");
    Js.log2("Failure!!", err);
    return(errMsg))
  });
};
```

This is the compiler error:

```
This has type:
    Js.Promise.t(Js.Promise.error) (defined as
      Js.Promise.t(Js.Promise.error))
  But somewhere wanted:
    Js.Promise.t(idTokenT) (defined as Js.Promise.t(idTokenT))

  The incompatible parts:
    Js.Promise.error (defined as Js.Promise.error)
    vs
    idTokenT
```

Any guidance would be appreciated. Thank you, sir.

**Comment by digitake** [comment]
can you try with redefine version of (>>|)

```
let (>>|) = (m: Js.Promise.t('a), f: Js.Promise.error => Js.Promise.t('b)) =>
  Js.Promise.catch(f, m);
```

It seems like type enforcement is too strict on the operation.

or try to return the same type `idTokenT` that is supposed to return when no exception has occurred.

**Comment by hew** [comment]
In situations like this, it's sometimes better to return a `Belt.Result`

```reason

let getToken = () =>
  getCurrentSession(auth, ())
  >>= (
    response => Belt.Result.Ok(decodeToken(response)) |> return
  )
  >>| (
    err => {
      let errMsg =
        err |> Js.Json.stringifyAny |> Js.Option.getWithDefault("");
      Js.log2("Failure!!", err);

      Belt.Result.Error(errMsg) |> return;
    }
  );


```

then assuming you have `let-anything` you could 

```reason

let _ = {
}

```

**Comment by hew** [comment]
In situations like this, it's sometimes better to return a `Belt.Result`

```reason
let getToken = () => {
  Belt.Result.(
    getCurrentSession(auth, ())
    >>= (response => Ok(decodeIdToken(response)) |> return)
    >>| (err => Error(err) |> return)
  );
};
```
That way, you give the compiler what it wants - the same type returned. But this way it's a variant type, so you can switch on it. 

```reason
let _ = {
  let%Await result = Auth.getToken();

  switch (result) {
    | Belt.Result.Ok(jwtToken) => //...,
    | Belt.Result.Error(err) => //...
    };
};

```

**Comment by hew** [comment]
If I know the `return` type can easily be cast from success/error into _one_ type (ie: `string`), then I will skip the `Belt.Result`, but if I want the freedom to return different types, then that's what I do.

**Comment by idkjs** [comment]
Damn, @hew, big fan. Thanks for the feedback, brother. Nice work on your hew.tools repo.

Looks like you are using [let-anything](https://github.com/jaredly/let-anything).

Let me try that.

**Comment by hew** [comment]
Thanks @idkjs  😀. 

Note that you don't necessarily need to use `let-anything` for what I'm proposing to work. 

`Js.Promise` as it's implemented here wants you to resolve _one_ type. So, by feeding it one variant type, you can return different things through those variants. Here, I use `Belt.Result`, but you could use any variant you want.
