### ISSUE TITLE
Add auto-return for catch as well

### ISSUE THREAD

**Issue by rolandpeelen** [digitake/bs-promise-monad#5]
Hi! Digging this stuff, makes it so much cleaner. I've added the following to mine just now:

```let (>>/) = (m: Js.Promise.t('a), f: Js.Promise.error => 'a) => Js.Promise.catch(e => return(f(e)), m);```

I would have made a PR, but the console is spewing errors at me when I try to compile and I'm not that familiar with Reason just yet :P

**Comment by digitake** [comment]
@rolandpeelen Very useful. Thanks so much. I put this in for you and credit you on README.md.
